version: '3.1'

services:
  db:
    image: mysql:8.0.33
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: filrouge2024
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: adminpassword
    ports:
      - '8080:80'

volumes:
  db_data:
