-- AlterTable
ALTER TABLE `UserInvitations` MODIFY `status` ENUM('JOINED', 'DISJOINED', 'WAITING_CREATOR_RESPONSE', 'WAITING_PARTICIPANT_RESPONSE', 'DECLINED_BY_CREATOR', 'DECLINED_BY_PARTICIPANT') NOT NULL DEFAULT 'WAITING_CREATOR_RESPONSE';
